const fs = require('fs');
const path = require('path');

function adf(text) {
  return { type: 'doc', version: 1, content: String(text).split(/\n+/).filter(Boolean).map((line) => ({ type: 'paragraph', content: [{ type: 'text', text: line }] })) };
}

class JiraCloud {
  constructor({ baseUrl = process.env.JIRA_BASE_URL, email = process.env.JIRA_EMAIL, apiToken = process.env.JIRA_API_TOKEN, projectKey = process.env.JIRA_PROJECT_KEY, fetchImpl = global.fetch } = {}) {
    this.baseUrl = String(baseUrl || '').replace(/\/+$/, ''); this.email = email; this.apiToken = apiToken; this.projectKey = projectKey; this.fetchImpl = fetchImpl;
  }
  configured() { return Boolean(this.baseUrl && this.email && this.apiToken && this.projectKey); }
  headers(extra = {}) { return { accept: 'application/json', authorization: `Basic ${Buffer.from(`${this.email}:${this.apiToken}`).toString('base64')}`, ...extra }; }
  async request(endpoint, { method = 'GET', body, headers = {} } = {}) {
    if (!this.configured()) throw new Error('Jira Cloud requires JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, and JIRA_PROJECT_KEY');
    const options = { method, headers: this.headers(headers) };
    if (body !== undefined) {
      if (body instanceof FormData) options.body = body;
      else { options.headers['content-type'] = 'application/json'; options.body = JSON.stringify(body); }
    }
    const response = await this.fetchImpl(`${this.baseUrl}${endpoint}`, options); const raw = await response.text();
    if (!response.ok) throw new Error(`Jira API ${method} ${endpoint} failed (${response.status}): ${raw.slice(0, 1000)}`);
    return raw ? JSON.parse(raw) : null;
  }
  async createDocumentationTask(documentName) {
    const result = await this.request('/rest/api/3/issue', { method: 'POST', body: { fields: { project: { key: this.projectKey }, summary: `Documentation Review - ${documentName}`, description: adf('Generated by Agent A'), issuetype: { name: 'Task' } } } });
    return { key: result.key, id: result.id, self: result.self, status: 'To Do' };
  }
  async attachGeneratedDocumentation(issueKey, filePath) {
    if (!fs.existsSync(filePath)) throw new Error(`Generated documentation not found: ${filePath}`);
    const form = new FormData(); form.append('file', new Blob([fs.readFileSync(filePath)], { type: 'text/markdown' }), path.basename(filePath));
    return this.request(`/rest/api/3/issue/${encodeURIComponent(issueKey)}/attachments`, { method: 'POST', body: form, headers: { 'X-Atlassian-Token': 'no-check' } });
  }
  async addFeedbackComment(issueKey, feedback) {
    const text = typeof feedback === 'string' ? feedback : [`Feedback ${feedback.id || ''}`.trim(), `Source: ${feedback.source || 'unknown'}`, `Section: ${feedback.targetSection || 'unspecified'}`, `Severity: ${feedback.severity || 'unspecified'}`, `Comment: ${feedback.comment || ''}`, feedback.suggestedChange ? `Suggested change: ${feedback.suggestedChange}` : ''].filter(Boolean).join('\n');
    return this.request(`/rest/api/3/issue/${encodeURIComponent(issueKey)}/comment`, { method: 'POST', body: { body: adf(text) } });
  }
  async getIssueStatus(issueKey) {
    const issue = await this.request(`/rest/api/3/issue/${encodeURIComponent(issueKey)}?fields=status,updated,summary`);
    return { issueKey: issue.key, status: issue.fields?.status?.name || 'Unknown', lastUpdate: issue.fields?.updated || null, summary: issue.fields?.summary || '' };
  }
  async availableTransitions(issueKey) { const result = await this.request(`/rest/api/3/issue/${encodeURIComponent(issueKey)}/transitions`); return result.transitions || []; }
  async updateIssueStatus(issueKey, targetStatus) {
    const workflow = ['To Do', 'In Progress', 'Review', 'Done'];
    if (!workflow.some((status) => status.toLowerCase() === String(targetStatus).toLowerCase())) throw new Error(`Unsupported Jira status: ${targetStatus}`);
    const current = await this.getIssueStatus(issueKey); const canonicalTarget = workflow.find((status) => status.toLowerCase() === String(targetStatus).toLowerCase());
    if (current.status.toLowerCase() === canonicalTarget.toLowerCase()) return current;
    const currentIndex = workflow.findIndex((status) => status.toLowerCase() === current.status.toLowerCase()); const targetIndex = workflow.indexOf(canonicalTarget);
    const steps = currentIndex >= 0 && currentIndex < targetIndex ? workflow.slice(currentIndex + 1, targetIndex + 1) : [canonicalTarget];
    for (const nextStatus of steps) {
      const transitions = await this.availableTransitions(issueKey);
      const transition = transitions.find((item) => item.to?.name?.toLowerCase() === nextStatus.toLowerCase()) || transitions.find((item) => item.name?.toLowerCase() === nextStatus.toLowerCase());
      if (!transition) throw new Error(`No Jira transition from current status to ${nextStatus} for ${issueKey}`);
      await this.request(`/rest/api/3/issue/${encodeURIComponent(issueKey)}/transitions`, { method: 'POST', body: { transition: { id: transition.id } } });
    }
    return this.getIssueStatus(issueKey);
  }
}

module.exports = { JiraCloud, adf };
