const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { JiraCloud } = require('../adapters/jiraCloud');

function jsonResponse(status, value) { return { ok: status >= 200 && status < 300, status, text: async () => value === null ? '' : JSON.stringify(value) }; }

test('Jira Cloud creates tasks, attaches Markdown, and adds ADF feedback comments', async () => {
  const calls = []; const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'jira-cloud-')); const file = path.join(temp, 'guide.md'); fs.writeFileSync(file, '# Guide\n');
  const jira = new JiraCloud({ baseUrl: 'https://example.atlassian.net/', email: 'user@example.com', apiToken: 'token', projectKey: 'DOC', fetchImpl: async (url, options) => {
    calls.push({ url, options });
    if (url.endsWith('/rest/api/3/issue')) return jsonResponse(201, { key: 'DOC-42', id: '42', self: `${url}/42` });
    if (url.endsWith('/attachments')) return jsonResponse(200, [{ id: 'attachment-1', filename: 'guide.md' }]);
    if (url.endsWith('/comment')) return jsonResponse(201, { id: 'comment-1' });
    return jsonResponse(404, { error: 'unexpected' });
  } });
  const issue = await jira.createDocumentationTask('guide.md'); await jira.attachGeneratedDocumentation(issue.key, file);
  await jira.addFeedbackComment(issue.key, { id: 'FB-001', source: 'PM', targetSection: 'FAQ', severity: 'high', comment: 'Add examples.' });
  const createBody = JSON.parse(calls[0].options.body);
  assert.equal(createBody.fields.summary, 'Documentation Review - guide.md'); assert.equal(createBody.fields.issuetype.name, 'Task');
  assert.equal(createBody.fields.description.content[0].content[0].text, 'Generated by Agent A');
  assert.equal(calls[1].options.headers['X-Atlassian-Token'], 'no-check'); assert.ok(calls[1].options.body instanceof FormData);
  const commentBody = JSON.parse(calls[2].options.body); assert.equal(commentBody.body.type, 'doc'); assert.match(JSON.stringify(commentBody), /Add examples/);
  assert.match(calls[0].options.headers.authorization, /^Basic /);
});

test('Jira Cloud discovers transition IDs and advances To Do through Done', async () => {
  let status = 'To Do'; const posts = []; const next = { 'To Do': ['11', 'In Progress'], 'In Progress': ['22', 'Review'], Review: ['33', 'Done'] };
  const jira = new JiraCloud({ baseUrl: 'https://example.atlassian.net', email: 'user@example.com', apiToken: 'token', projectKey: 'DOC', fetchImpl: async (url, options) => {
    if (url.includes('?fields=status')) return jsonResponse(200, { key: 'DOC-42', fields: { status: { name: status }, updated: '2026-06-21T10:00:00.000+0000', summary: 'Documentation Review' } });
    if (url.endsWith('/transitions') && options.method === 'GET') { const transition = next[status]; return jsonResponse(200, { transitions: transition ? [{ id: transition[0], name: transition[1], to: { name: transition[1] } }] : [] }); }
    if (url.endsWith('/transitions') && options.method === 'POST') { const id = JSON.parse(options.body).transition.id; posts.push(id); status = Object.values(next).find((item) => item[0] === id)[1]; return jsonResponse(204, null); }
    return jsonResponse(404, {});
  } });
  const result = await jira.updateIssueStatus('DOC-42', 'Done');
  assert.deepEqual(posts, ['11', '22', '33']); assert.equal(result.status, 'Done'); assert.equal(result.issueKey, 'DOC-42');
});
