from __future__ import annotations
from collections import Counter
from datetime import datetime
from typing import Any


def _escape(value: Any) -> str:
    return str(value).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)").replace("\n", " ")


def _build_pdf_pages(pages: list[list[str]]) -> bytes:
    objects: list[bytes] = []
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    page_ids = [3 + i * 2 for i in range(len(pages))]
    objects.append(f"<< /Type /Pages /Kids [{' '.join(f'{i} 0 R' for i in page_ids)}] /Count {len(pages)} >>".encode())
    font_id = 3 + len(pages) * 2
    for index, lines in enumerate(pages):
        page_id = page_ids[index]
        content_id = page_id + 1
        objects.append(f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 {font_id} 0 R >> >> /Contents {content_id} 0 R >>".encode())
        commands = ["BT", "/F1 9 Tf", "45 750 Td", "12 TL"]
        for line in lines:
            commands.append(f"({_escape(line)[:115]}) Tj T*")
        commands.extend([f"(Page {index + 1} of {len(pages)} | CONFIDENTIAL | Generated by Compliance Platform) Tj", "ET"])
        content = "\n".join(commands).encode("latin-1", "replace")
        objects.append(f"<< /Length {len(content)} >>\nstream\n".encode() + content + b"\nendstream")
    objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, obj in enumerate(objects, 1):
        offsets.append(len(output)); output.extend(f"{number} 0 obj\n".encode() + obj + b"\nendobj\n")
    xref = len(output)
    output.extend(f"xref\n0 {len(objects)+1}\n0000000000 65535 f \n".encode())
    for offset in offsets[1:]: output.extend(f"{offset:010d} 00000 n \n".encode())
    output.extend(f"trailer << /Size {len(objects)+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF".encode())
    return bytes(output)


def generate_pdf(template: dict[str, Any], rows: list[dict[str, Any]], resolved: dict[str, str], csv_url: str, generated_at: datetime) -> tuple[bytes, int]:
    limit = min(len(rows), 10_000)
    policies = Counter(str(r.get("policy", "Unspecified")) for r in rows if r.get("flagged", True))
    channels = Counter(str(r.get("channel", "Unspecified")) for r in rows)
    grouping = (template.get("grouping_dimensions") or ["channel"])[0]
    groups = Counter(str(r.get(grouping, "Unspecified")) for r in rows)
    pages: list[list[str]] = [[
        template["name"], "", f"Period: {resolved['start_date']} to {resolved['end_date']}",
        f"Generated: {generated_at.isoformat()}", f"Tenant: {template['tenant_id']}", "", "CONFIDENTIAL",
        "Generated by Compliance Platform",
    ]]
    summary = ["EXECUTIVE SUMMARY", "", f"Total messages in scope: {len(rows):,}", f"Flagged messages: {sum(bool(r.get('flagged')) for r in rows):,}", "", "Top policies triggered:"]
    summary += [f"  {name}: {count:,}" for name, count in policies.most_common(5)]
    summary += ["", "Channel breakdown:"] + [f"  {name}: {count:,}" for name, count in channels.most_common()]
    summary += ["", f"GROUPED STATISTICS — {grouping}"] + [f"  {name}: {count:,}" for name, count in groups.most_common()]
    pages.append(summary)
    columns = template["columns"]
    lines = ["DETAILED DATA TABLE", " | ".join(columns)]
    if len(rows) > limit:
        lines += [f"Showing {limit:,} of {len(rows):,} rows. Download full dataset (CSV): {csv_url}"]
    for row in rows[:limit]:
        lines.append(" | ".join(str(row.get(column, "")) for column in columns))
        if len(lines) >= 55:
            pages.append(lines); lines = ["DETAILED DATA TABLE (continued)", " | ".join(columns)]
    if len(lines) > 2 or limit == 0: pages.append(lines)
    return _build_pdf_pages(pages), limit
